site_name: コリンのスペース
site_description: Colin's Space
site_url: 'https://csl122.com/'
site_author: Shiliang Chen
repo_url: 'https://github.com/csl122/mkdocs'
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: images/avt.png
  logo: images/avt.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: white
      accent: cyan
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: black
      accent: cyan
  icon:
    # logo: material/apple-keyboard-command
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - Home:
      - index.md
      - Bio: home/bio.md
      # - 术语: GettingStarted/term.md
      # - 声明: GettingStarted/state.md
      # - 贡献指南: GettingStarted/contributing.md
  - AIGC:
      - aigc/index.md
      - Stable Diffusion: aigc/Stable Diffusion.md
  - NLP:
      - nlp/index.md
      - Natural Language Processing: nlp/Natural Language Processing.md
  - ML/DL:
      - ml/index.md
      - Deep Learning: ml/Deep Learning.md
      - ML for Imaging: ml/Machine Learning for Imaging.md
      - NumPy: ml/numpy.md
      - PyTorch: ml/PyTorch.md
  - Mac: 
      - mac/index.md
      - Mac: mac/Mac.md
  - Linux: 
      - linux/index.md
      - Vim: linux/Vim.md
      - AstroNvim: linux/AstroNvim.md
      - Starship: linux/Starship.md
      - Tmux: linux/Tmux.md
  - Networking: 
      - networking/index.md
      - Nginx: networking/Nginx.md
      - Nginx Proxy Manager: networking/Nginx Proxy Manager.md
  - Game: 
      - game/index.md

# plugins:
#   - social

extra:
  homepage: https://csl122.com
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/csl122
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/csl122
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/csl122/
    - icon: fontawesome/solid/paper-plane
      link: mailto:csl122@hotmail.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
copyright: |
  &copy; 2023 <a href="https://github.com/csl122"  target="_blank" rel="noopener">Shiliang Chen</a>
